In [1]:
import torch#此例是模拟f=（x1+x2）*z的前向传播同时计算局部梯度过程
x=torch.tensor([-2.,5.])
x.requires_grad_(True)#申请存放对x求完导数的结果的空间
q=x.sum()#q=x1+x2=-2.0+5.0
q.backward()#对x1、x2分别求导其值都等于1
z=torch.tensor([-4.])
z.requires_grad_(True)#申请存放对z求完导数的结果的空间
q_tensor=torch.tensor([q])#q是一个标量，不能申请空间，所以要把q变成个tensor
q_tensor.requires_grad_(True)
print(z,q_tensor)
f=q_tensor*z
f.backward()
print(x.grad)
print(q_tensor.grad)
print(z.grad)
# print(f)
print(q_tensor.grad*x.grad)#反向传播求f对x1、x2求导的结果（是把前向传播路径中的局部梯度都乘起来）



tensor([-4.], requires_grad=True) tensor([3.], requires_grad=True)
tensor([1., 1.])
tensor([-4.])
tensor([3.])
tensor([-4., -4.])
